<Project>

  <PropertyGroup Condition="$(MSBuildProjectName.Contains('Test')) == 'False'">
    <Copyright>Copyright (c) Nivaes Systems S.L.</Copyright>
    <PackageProject>https://github.com/Nivaes/Nivaes.Otel.backend</PackageProject>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
    <PackageIcon>icon.png</PackageIcon>
    <Authors>Nivaes Systems</Authors>
    <Company>Nivaes Systems</Company>
    <Owners>Nivaes</Owners>
    <PackageReleaseNotes>https://www.nivaes.com</PackageReleaseNotes>
    <PackageRequireLicenseAcceptance>false</PackageRequireLicenseAcceptance>
    <RepositoryUrl>https://github.com/Nivaes/Nivaes.IoC</RepositoryUrl>
    <RepositoryType>git</RepositoryType>
    <Product>$(AssemblyName) ($(TargetFramework))</Product>
  </PropertyGroup>

  <PropertyGroup>
    <NoWarn>$(NoWarn);1591;NU1507</NoWarn>
  </PropertyGroup>

  <PropertyGroup>
    <NeutralLanguage>en</NeutralLanguage>
    <VersionPrefix>0.0.1</VersionPrefix>
    <VersionSuffix>dev-001</VersionSuffix>
  </PropertyGroup>

  <PropertyGroup>
    <RestoreImplicitPackages>true</RestoreImplicitPackages>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <RunAnalyzersDuringBuild>true</RunAnalyzersDuringBuild>
    <RunAnalyzersDuringLiveAnalysis>true</RunAnalyzersDuringLiveAnalysis>

    <EnablePackageValidation>true</EnablePackageValidation>
    <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
  </PropertyGroup>

  <PropertyGroup>
    <IsTestProject>$(MSBuildProjectName.Contains('UnitTest'))</IsTestProject>
    <IsBenchmarksProject>$(MSBuildProjectName.Contains('Benchmarks'))</IsBenchmarksProject>

    <GenerateDocumentationFile Condition=" '$(Configuration)' == 'Release' ">true</GenerateDocumentationFile>
    <!-- <GeneratePackageOnBuild Condition=" '$(Configuration)' == 'Release' and '$(IsTestProject)' != 'true' and '$(IsBenchmarksProject)' != 'true'">true</GeneratePackageOnBuild> -->
  </PropertyGroup>

  <!-- <PropertyGroup>

    <SymbolPackageFormat>snupkg</SymbolPackageFormat>
    <IncludeSymbols>true</IncludeSymbols>
    <AllowedOutputExtensionsInPackageBuildOutputFolder>$(AllowedOutputExtensionsInPackageBuildOutputFolder);.pdb</AllowedOutputExtensionsInPackageBuildOutputFolder>
    <EmbedUntrackedSources>true</EmbedUntrackedSources>

    <DesignTimeBuild>false</DesignTimeBuild>
    <DebugType>portable</DebugType>
    <DebugSymbols>true</DebugSymbols>

  </PropertyGroup> -->

</Project>
